apiVersion: v2
name: data-platform
description: All-in-one ML Platform - MongoDB + PostgreSQL + MLflow + Kafka
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: mongodb
    version: 18.1.10
    repository: https://charts.bitnami.com/bitnami

  - name: postgresql
    version: 18.1.13
    repository: https://charts.bitnami.com/bitnami

  - name: minio
    version: 17.0.21
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
    
  - name: mlflow
    version: 1.8.0
    repository: "https://community-charts.github.io/helm-charts"

  - name: kafka
    version: 32.4.3
    repository: https://charts.bitnami.com/bitnami