apiVersion: v2
name: data-platform
description: All-in-one ML Platform - MongoDB + PostgreSQL + MLflow + Kafka
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: mongodb
    version: 18.1.10
    repository: https://charts.bitnami.com/bitnami

  - name: postgresql
    version: 18.1.13
    repository: https://charts.bitnami.com/bitnami

  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
    
  - name: mlflow
    version: 1.8.0
    repository: "https://community-charts.github.io/helm-charts"

  - name: strimzi-kafka-operator
    version: 0.49.1
    repository: https://strimzi.io/charts/
  
  - name: kube-prometheus-stack
    version: 80.2.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled

  - name: loki
    version: 6.48.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled

  - name: alloy
    version: 1.5.0
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled